version: '3.7'
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=H2ow@ter
      - POSTGRES_DB=emsdb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'